### ISSUE TITLE
[BUG] unexpected status code 404: http://prometheus-msteams:2000/alertmanager

### ISSUE THREAD

**Issue by cubed-it** [prometheus-msteams/prometheus-msteams#117]
I followed the steps provided and deployed the chart: https://github.com/prometheus-msteams/prometheus-msteams/tree/master/chart/prometheus-msteams
I removed the extraEnvs proxy and set the teams webhook. Everything else is as described.

However I only get 404 from the alertmaneger and also if I query with wget:
```
{"caller":"transport.go:29","level":"debug","request_path_added":"high_priority_channel","ts":"2020-04-21T13:08:53.591613574Z"}
{"caller":"transport.go:29","level":"debug","request_path_added":"low_priority_channel","ts":"2020-04-21T13:08:53.591718275Z"}
{"branch":"HEAD","build_date":"2020-03-04T16:54:43+0000","caller":"main.go:291","commit":"e2f6d6e","listen_http_addr":":2000","ts":"2020-04-21T13:08:53.688537431Z","version":"v1.3.3"}
```

```
level=error ts=2020-04-21T12:11:13.507Z caller=dispatch.go:301 component=dispatcher msg="Notify for alerts failed" num_alerts=1 err="cancelling notify retry for \"webhook\" due to unrecoverable error: unexpected status code 404: http://prometheus-msteams:2000/alertmanager"
level=error ts=2020-04-21T12:12:54.812Z caller=notify.go:372 component=dispatcher msg="Error on notify" err="cancelling notify retry for \"webhook\" due to unrecoverable error: unexpected status code 404: http://prometheus-msteams:2000/alertmanager" context_err=null
level=error ts=2020-04-21T12:12:54.812Z caller=dispatch.go:301 component=dispatcher msg="Notify for alerts failed" num_alerts=3 err="cancelling notify retry for \"webhook\" due to unrecoverable error: unexpected status code 404: http://prometheus-msteams:2000/alertmanager"
level=error ts=2020-04-21T12:16:13.507Z caller=notify.go:372 component=dispatcher msg="Error on notify" err="cancelling notify retry for \"webhook\" due to unrecoverable error: unexpected status code 404: http://prometheus-msteams:2000/alertmanager" context_err=null
```

What is wrong? What can I do to fix or evaluate the problem?

Thanks!

**Comment by bzon** [comment]
@cubed-it the request path that you are using does not exists in prometheus msteams. 

You should be using /low_priority_channel and /high_priority_channel and not /alertmanager.

Can you also provide the helm values file redacting the webhook url or the configmap that the helm generated.

**Comment by cubed-it** [comment]
Damn, now that you mention it, it's obvious... And I even read the main readme ;) 
It works now, thanks for the great work and the quick help!!

**Comment by kosminv** [comment]
i have almost the same issue, and i cannot figure out where could be the problem.

alertmanager.yaml

global:
  resolve_timeout: 5m
receivers:
- name: devnull
- name: prometheus-msteams-warning
  webhook_configs:
  - url: "http://prometheus-msteams:2000/alertmanager-warning"
    send_resolved: true
- name: prometheus-msteams-critical
  webhook_configs:
  - url: "http://prometheus-msteams:2000/alertmanager-critical"
route:
  group_by:['...']
  group_interval: 1m
  group_wait: 1m
  repeat_interval: 5m
  receiver: devnull
  routes:
  - receiver: prometheus-msteams-warning
    match:
      severity: warning
    continue: true
  - receiver: prometheus-msteams-critical
    match:
      severity: critical

connectors:
 -alertmanager-warning: https://office.com/webhookb2/2cd99898-b75f-44f7-8be8-ebd920435400@06acdef6-af30-4834-beac-4bab6f8f226f/IncomingWebhook/2cb0494d46864f67a0e31631388bb62b/365e6ad4-9927-4083-ab67-4d17f4fdabfb
 -alertmanager-critical: https://office.com/webhookb2/2cd99898-b75f-44f7-8be8-ebd920435400@06acdef6-af30-4834-beac-4bab6f8f226f/IncomingWebhook/b97ab326a7e749f689537a668b1511d2/365e6ad4-9927-4083-ab67-4d17f4fdabfb

msteams pod logs:
{"caller":"transport.go:43","level":"debug","request_path_added":"/_dynamicwebhook/*","ts":"2022-01-18T08:53:54.603173056Z"}
{"branch":"HEAD","build_date":"2021-05-02T12:17:32+0000","caller":"main.go:364","commit":"3bdd0e3","listen_http_addr":":2000","ts":"2022-01-18T08:53:54.6037094Z","version":"v1.5.0"}

alertmanager-prometheus-prometheus-oper-alertmanager-0 pod logs:

level=error ts=2022-01-19T07:13:57.412Z caller=dispatch.go:309 component=dispatcher msg="Notify for alerts failed" num_alerts=1 err="prometheus-msteams-warning/webhook[0]: notify retry canceled due to unrecoverable error after 1 attempts: unexpected status code 404: http://prometheus-msteams:2000/alertmanager-warning"
level=error ts=2022-01-19T07:14:02.985Z caller=dispatch.go:309 component=dispatcher msg="Notify for alerts failed" num_alerts=1 err="prometheus-msteams-critical/webhook[0]: notify retry canceled due to unrecoverable error after 1 attempts: unexpected status code 404: http://prometheus-msteams:2000/alertmanager-critical"

**Comment by helinyi** [comment]
> problem sending alerts to msteams #120

Did you solve this issue now?
