### ISSUE TITLE
[BUG]Helm chart unavailable 

### ISSUE THREAD

**Issue by greeshma156** [prometheus-msteams/prometheus-msteams#184]
**Describe the bug**
The helm chart repo mentioned in the documentation sends 404 when tried to retrieve the chart. 

`helm repo add prometheus-msteams https://prometheus-msteams.github.io/prometheus-msteams/`
`helm repo update`
`helm show chart prometheus-msteams`
 **Error: failed to download "prometheus-msteams" (hint: running `helm repo update` may help)**

The add and update commands work but fails to access the helm.

**Comment by Knappek** [comment]
@greeshma156 you using a wrong command. `helm show chart prometheus-msteams` inspects a chart that has been already deployed on your current cluster context. In order to do that, you first have to install the chart with `helm install ...`.

You can verify that the chart has been successfully downloaded using `helm search repo`.
