### ISSUE TITLE
[FEATURE] Removal of default resources values in helm chart

### ISSUE THREAD

**Issue by JuanPabloSGU** [prometheus-msteams/prometheus-msteams#271]
**Is your feature request related to a problem? Please describe.**
This feature is about removing the default resources values in the helm chart. The reason for this is that having default values prevents chart users from removing it on their side. 

**Describe the solution you'd like**
The solution would be to comment out the default values.

**Comment by ckotzbauer** [comment]
You should be able to remove them by `resources: {}` or `resources: null`.

**Comment by jemag** [comment]
Unfortunately there is this long standing bug https://github.com/helm/helm/issues/9027 that prevents this when the chart is used in dependencies (for example this is the common use case in ArgoCD).

I realize this is not on your side, but could we at least remove the cpu limit since nowadays cpu limits are considered often more detrimental than anything.

**Comment by ckotzbauer** [comment]
Okay, I was not aware of this issue, thanks. Would you mind opening a PR for that (the whole `resources`)? Then we get this in.
